name: ML Model CI

on:
  push:
    branches:
      - main

jobs:
  build-train-evaluate:
    runs-on: self-hosted

    steps:
      - name: Create Unique Workspace
        run: |
          $uniqueDir = "runner_work_" + (Get-Date -Format "yyyyMMddHHmmss")
          New-Item -ItemType Directory -Force -Path $uniqueDir
          echo "Unique workspace created: $uniqueDir"
          echo "WORKSPACE_DIR=$uniqueDir" | Out-File -FilePath $Env:GITHUB_ENV -Append
        shell: powershell

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: ${{ env.WORKSPACE_DIR }}

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Create virtual environment
        run: |
          cd ${{ env.WORKSPACE_DIR }}
          python -m venv .venv
          echo "Virtual environment created."

      - name: Activate virtual environment and Install dependencies
        run: |
          cd ${{ env.WORKSPACE_DIR }}
          .\.venv\Scripts\Activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "Dependencies installed."

      - name: Build the model
        run: |
          cd ${{ env.WORKSPACE_DIR }}
          .\.venv\Scripts\Activate
          python model.py

      - name: Train the model
        run: |
          cd ${{ env.WORKSPACE_DIR }}
          .\.venv\Scripts\Activate
          python train.py

      - name: Evaluate the model
        run: |
          cd ${{ env.WORKSPACE_DIR }}
          .\.venv\Scripts\Activate
          python model_eval.py

      - name: Commit and push if changes
        run: |
          cd ${{ env.WORKSPACE_DIR }}
          .\.venv\Scripts\Activate
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f .
          git commit -m "Automated model update" -a || echo "No changes to commit"
          git push
