name: Seph's V1 Model CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Train model
      run: |
        python train.py # This script will import and use model.py for training

    - name: Evaluate model
      run: |
        python model_eval.py # Ensure you have a model_eval.py for model evaluation

    - name: Upload trained model
      uses: actions/upload-artifact@v2
      with:
        name: trained-model
        path: Seph_model/ # Adjusted to the SavedModel directory