name: Seph's V1 Model CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          # Activate virtual environment
          if [ "$RUNNER_OS" == "Windows" ]; then
            .\venv\Scripts\Activate.ps1
          else
            source venv/bin/activate
          fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          # Ensure virtual environment is active
          source venv/bin/activate
          python train.py # This script will import and use model.py for training

      - name: Evaluate model
        run: |
          # Ensure virtual environment is active
          source venv/bin/activate
          python model_eval.py # This script will import and use model.py for model evaluation

      - name: Upload trained model
        uses: actions/upload-artifact@v2
        with:
          name: trained-model
          path: Seph_model/ # Adjust the path as necessary to where the model is saved
