name: ML Model CI

on:
  push:
    branches:
      - main

jobs:
  build-train-evaluate:
    runs-on: self-hosted

    steps:
      - name: Create Unique Workspace
        run: |
          $uniqueDir = "runner_work_" + (Get-Date -Format "yyyyMMddHHmmss")
          New-Item -ItemType Directory -Force -Path $uniqueDir
          echo "Unique workspace created: $uniqueDir"
          echo "WORKSPACE_DIR=$uniqueDir" | Out-File -FilePath $Env:GITHUB_ENV -Append
        shell: powershell

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: ${{ env.WORKSPACE_DIR }}

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Create virtual environment
        run: |
          cd ${{ env.WORKSPACE_DIR }}
          python -m venv .venv
          echo "Virtual environment created."

      - name: Install dependencies
        run: |
          cd ${{ env.WORKSPACE_DIR }}
          .\.venv\Scripts\Activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "Dependencies installed."

      - name: Run scripts
        run: |
          cd ${{ env.WORKSPACE_DIR }}
          .\.venv\Scripts\Activate
          python model.py
          python train.py
          python model_eval.py
          echo "Scripts executed."

      - name: Commit and push changes
        run: |
          cd ${{ env.WORKSPACE_DIR }}
          .\.venv\Scripts\Activate
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --staged --quiet || git commit -m "Update from workflow"
          git push
