name: ML Model CI

on:
  push:
    branches:
      - main

jobs:
  build-train-evaluate:
    runs-on: self-hosted

    steps:
      - name: Create virtual environment
        run: |
          python -m venv .venv
          .\.venv\Scripts\Activate
          python -m pip install --upgrade pip

      - name: Checkout repository into a specific directory
        uses: actions/checkout@v2
        with:
          path: 'repo'

      - name: Install dependencies
        run: |
          .\.venv\Scripts\Activate
          pip install -r repo/requirements.txt

      - name: Build the model
        run: |
          .\.venv\Scripts\Activate
          python repo/model.py

      - name: Train the model
        run: |
          .\.venv\Scripts\Activate
          python repo/train.py

      - name: Evaluate the model
        run: |
          .\.venv\Scripts\Activate
          python repo/model_eval.py

      - name: Commit and push if changes
        run: |
          .\.venv\Scripts\Activate
          cd repo
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f .
          git commit -m "Automated model update" -a || echo "No changes to commit"
          git push
