name: Seph's V1 Model CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-train-evaluate:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Build the model
        run: python model.py
      
      - name: Train the model
        run: python train.py
      
      - name: Evaluate the model
        run: python model_eval.py
      
      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f .
          git commit -m "Automated model update" -a || echo "No changes to commit"
          git push