name: ML Model CI

on:
  push:
    branches:
      - main

jobs:
  build-train-evaluate:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # This will use the latest stable version of Python 3

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          .\venv\Scripts\Activate

      - name: Install dependencies
        run: |
          .\venv\Scripts\Activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build the model
        run: |
          .\venv\Scripts\Activate
          python model.py

      - name: Train the model
        run: |
          .\venv\Scripts\Activate
          python train.py

      - name: Evaluate the model
        run: |
          .\venv\Scripts\Activate
          python model_eval.py

      - name: Commit and push if changes
        run: |
          .\venv\Scripts\Activate
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f .
          git commit -m "Automated model update" -a || echo "No changes to commit"
          git push
